providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npx pnpm@9 install --no-frozen-lockfile"]

[phases.build]
cmds = ["npx pnpm@9 --filter @45cm/marketing-api... --filter @45cm/marketing-worker... build"]

[start]
cmd = "node start-mkt.js"
